### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by vishichoudhary** [vishichoudhary/ballAndBridge#2]

**Comment by Bharat123rox** [comment]
@vishichoudhary Can I take this?

**Comment by vishichoudhary** [comment]
Yeah .

**Comment by vishichoudhary** [comment]
If possible write a contribute.md too in which specify that make a new branch and do changes and then send a pull requests @Bharat123rox

**Comment by Bharat123rox** [comment]
Sent Pull Request #4  see it

**Comment by vishichoudhary** [comment]
Yeah merged it .

**Comment by Bharat123rox** [comment]
What should I do for Contributing.md?

**Comment by vishichoudhary** [comment]
Ok let me create a new issue for it. It will be beneficial for both of us :-)
